name: "unit tests"

on: [ "pull_request", "push" ]

jobs:
    unit-tests:
        name: "unit tests"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                symfony-version:
                    - "5.3.*"
                php-version:
                    - "7.2"
                    - "7.3"
                    - "7.4"
                    - "8.0"
                dependencies:
                    - "lowest"
                    - "highest"

        steps:
            -   name: "checkout"
                uses: "actions/checkout@v2"

            -   name: "installing PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    tools: composer:v2, cs2pr
                    extensions: intl, bcmath, curl, openssl, mbstring, pdo, pdo_sqlite
                    coverage: pcov
                    ini-values: memory_limit=-1

            -   name: "caching dependencies"
                uses: "actions/cache@v2"
                with:
                    path: |
                        ~/.composer/cache
                        vendor
                    key: "php-${{ matrix.php-version }}"
                    restore-keys: "php-${{ matrix.php-version }}"

            -   name: "configuring composer platform"
                if: (startsWith(matrix.php, '8.0'))
                run: composer config platform.php 7.4.99

            -   name: "install lowest dependencies"
                if: ${{ matrix.dependencies == 'lowest' }}
                run: composer update --prefer-lowest --no-interaction --no-progress --prefer-dist

            -   name: "install highest dependencies"
                if: ${{ matrix.dependencies == 'highest' }}
                run: |
                    composer require --no-update symfony/config=${{ matrix.symfony-version }} symfony/http-kernel=${{ matrix.symfony-version }} symfony/dependency-injection=${{ matrix.symfony-version }} symfony/options-resolver=${{ matrix.symfony-version }}
                    composer require --no-update --dev symfony/framework-bundle=${{ matrix.symfony-version }} symfony/yaml=${{ matrix.symfony-version }}
                    composer update --no-interaction --no-progress --prefer-dist

            -   name: "installing phpunit"
                run: vendor/bin/simple-phpunit install

            -   name: "running unit tests"
                run: vendor/bin/simple-phpunit
